// bpf/http_trace.c — AuralisAPI eBPF HTTP Telemetry Program
//
// Hooks: kprobe/tcp_sendmsg
// Purpose: Intercept outgoing TCP payloads and extract HTTP request metadata
//          (method, path, pid, tid) at kernel level before TLS encryption.
//
// Map types:
//   BPF_MAP_TYPE_RINGBUF — streaming events to userspace
//   BPF_MAP_TYPE_HASH    — optional PID filter populated from userspace
//
// Kernel compatibility: Linux >= 5.8 (ring buffer support)
// Target arch: x86-64 (-D__TARGET_ARCH_x86, -target amd64)
// Compiler: clang with BPF target
// Go binding: generated by bpf2go (see //go:generate in main.go)

//go:build ignore
// +build ignore

// Pull in x86-64 struct pt_regs before BPF tracing headers so that
// PT_REGS_PARM macros have the full struct definition available.
#include <asm/ptrace.h>

#include <linux/bpf.h>
#include <linux/types.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>

// ── Constants ─────────────────────────────────────────────────────────────────
#define MAX_PATH_LEN   128
#define MAX_METHOD_LEN 8
#define MAX_BUF_LEN    256

// ── BPF CO-RE shadow structs ───────────────────────────────────────────────────
// preserve_access_index enables BTF-based field relocation at load time,
// making the program portable across kernel versions >= 5.2.
// Only fields we access need to be listed.

struct iovec {
    void              *iov_base;
    __kernel_size_t    iov_len;
} __attribute__((preserve_access_index));

struct iov_iter {
    __u8              iter_type;
    __u8              nofault;
    __u8              data_source;
    __u8              user_backed;
    __kernel_size_t   iov_offset;
    __kernel_size_t   count;
    const struct iovec *iov;
} __attribute__((preserve_access_index));

struct sock; // forward — not dereferenced

struct msghdr {
    void              *msg_name;
    int                msg_namelen;
    int                msg_inq;
    struct iov_iter    msg_iter;
} __attribute__((preserve_access_index));

// ── Event structure published to userspace via ring buffer ───────────────────
// WARNING: Go's binary.LittleEndian parsing in live.go must match this exact
// layout including alignment padding. Do NOT reorder fields.
struct http_event_t {
    __u32 pid;                    // offset  0, 4 bytes
    __u32 tid;                    // offset  4, 4 bytes
    __u64 timestamp_ns;           // offset  8, 8 bytes
    __u16 status_code;            // offset 16, 2 bytes
    char  method[MAX_METHOD_LEN]; // offset 18, 8 bytes
    char  path[MAX_PATH_LEN];     // offset 26, 128 bytes
    // implicit tail padding: 6 bytes → sizeof = 160
};

// ── Ring buffer map ───────────────────────────────────────────────────────────
struct {
    __uint(type,        BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);   // 256 KB
} events SEC(".maps");

// ── PID filter map (optional — populated from userspace to trace specific PIDs)
struct {
    __uint(type,        BPF_MAP_TYPE_HASH);
    __uint(max_entries, 1024);
    __type(key,   __u32);
    __type(value, __u8);
} pid_filter SEC(".maps");

// ── Helper: identify HTTP method in the first bytes of a buffer ───────────────
// Returns 0 on success and writes the null-terminated method string.
// Returns -1 if no recognisable HTTP method is found (non-HTTP traffic).
static __always_inline int parse_http_method(const char *buf, __u32 buf_len,
                                              char *out, __u32 out_len) {
    if (buf_len < 4 || out_len < MAX_METHOD_LEN)
        return -1;

    char tmp[MAX_METHOD_LEN] = {};
    if (bpf_probe_read_user(tmp, sizeof(tmp) - 1, buf) < 0)
        return -1;

    if (tmp[0]=='G' && tmp[1]=='E' && tmp[2]=='T' && tmp[3]==' ') {
        __builtin_memcpy(out, "GET\0", 4);  return 0;
    }
    if (tmp[0]=='P' && tmp[1]=='O' && tmp[2]=='S' && tmp[3]=='T') {
        __builtin_memcpy(out, "POST\0", 5); return 0;
    }
    if (tmp[0]=='P' && tmp[1]=='U' && tmp[2]=='T' && tmp[3]==' ') {
        __builtin_memcpy(out, "PUT\0", 4);  return 0;
    }
    if (tmp[0]=='D' && tmp[1]=='E' && tmp[2]=='L' && tmp[3]=='E') {
        __builtin_memcpy(out, "DELETE\0", 7); return 0;
    }
    if (tmp[0]=='P' && tmp[1]=='A' && tmp[2]=='T' && tmp[3]=='C') {
        __builtin_memcpy(out, "PATCH\0", 6); return 0;
    }
    return -1;
}

// ── kprobe: tcp_sendmsg ───────────────────────────────────────────────────────
// BPF_KPROBE extracts typed args from pt_regs using x86-64 registers.
// Requires __TARGET_ARCH_x86 defined (passed via -cflags) and
// asm/ptrace.h for the full struct pt_regs definition.
// Signature: int tcp_sendmsg(struct sock *sk, struct msghdr *msg, size_t size)
SEC("kprobe/tcp_sendmsg")
int BPF_KPROBE(kprobe_tcp_sendmsg, struct sock *sk, struct msghdr *msg, __kernel_size_t size)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    __u32 pid      = pid_tgid >> 32;
    __u32 tid      = (__u32)pid_tgid;

    __u8 *tracked = bpf_map_lookup_elem(&pid_filter, &pid);
    (void)tracked;
    // if (!tracked) return 0;  // enable for PID filtering

    // Read msg->msg_iter.iov via CO-RE (preserve_access_index relocates offsets)
    const struct iovec *iov = NULL;
    if (bpf_probe_read_kernel(&iov, sizeof(iov),
            __builtin_preserve_access_index(&msg->msg_iter.iov)) < 0)
        return 0;
    if (!iov)
        return 0;

    void *iov_base = NULL;
    __kernel_size_t iov_len = 0;
    if (bpf_probe_read_kernel(&iov_base, sizeof(iov_base),
            __builtin_preserve_access_index(&iov->iov_base)) < 0)
        return 0;
    if (bpf_probe_read_kernel(&iov_len, sizeof(iov_len),
            __builtin_preserve_access_index(&iov->iov_len)) < 0)
        return 0;

    if (!iov_base || iov_len < 4)
        return 0;

    // Quick HTTP method check — discard non-HTTP traffic early
    char method_buf[MAX_METHOD_LEN] = {};
    if (parse_http_method(iov_base, (__u32)iov_len, method_buf, MAX_METHOD_LEN) < 0)
        return 0;

    // Reserve a ring buffer slot
    struct http_event_t *evt = bpf_ringbuf_reserve(&events, sizeof(*evt), 0);
    if (!evt)
        return 0;

    evt->pid          = pid;
    evt->tid          = tid;
    evt->timestamp_ns = bpf_ktime_get_ns();
    evt->status_code  = 0;

    __builtin_memcpy(evt->method, method_buf, MAX_METHOD_LEN);

    // Read the first MAX_BUF_LEN bytes to extract the URL path
    char buf[MAX_BUF_LEN] = {};
    __u32 read_len = iov_len < MAX_BUF_LEN ? (__u32)iov_len : MAX_BUF_LEN;
    if (bpf_probe_read_user(buf, read_len, iov_base) < 0) {
        bpf_ringbuf_discard(evt, 0);
        return 0;
    }

    // Locate start of path: first space after method token
    int path_start = -1;
    #pragma unroll
    for (int i = 0; i < MAX_METHOD_LEN + 1 && i < MAX_BUF_LEN; i++) {
        if (buf[i] == ' ') {
            path_start = i + 1;
            break;
        }
    }

    if (path_start < 0 || path_start >= MAX_BUF_LEN) {
        bpf_ringbuf_discard(evt, 0);
        return 0;
    }

    // Copy path bytes until space / CR / LF or buffer end
    #pragma unroll
    for (int i = 0; i < MAX_PATH_LEN - 1; i++) {
        int idx = path_start + i;
        if (idx >= MAX_BUF_LEN)
            break;
        char c = buf[idx];
        if (c == ' ' || c == '\r' || c == '\n' || c == '\0')
            break;
        evt->path[i] = c;
    }

    bpf_ringbuf_submit(evt, 0);
    return 0;
}

char _license[] SEC("license") = "GPL";
