// sensor/live.go — Live eBPF sensor implementation.
//
// Loads the bpf2go-generated eBPF objects (compiled from bpf/http_trace.c,
// bpf/sensor.c, and bpf/go_tls_trace.c), attaches probes, reads events from
// the ring buffers, and publishes structured JSON events to Redis Streams.
//
// Requirements:
//   - Linux kernel >= 5.8  (BPF_MAP_TYPE_RINGBUF)
//   - CAP_BPF + CAP_SYS_ADMIN (or run as root)
//   - SENSOR_MODE=live

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64 -cflags "-O2 -g -Wall -Werror -D__TARGET_ARCH_x86" HttpTrace ../bpf/http_trace.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64 -cflags "-O2 -g -Wall -Werror -D__TARGET_ARCH_x86" Sensor ../bpf/sensor.c
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target amd64 -cflags "-O2 -g -Wall -Werror -D__TARGET_ARCH_x86" GoTls ../bpf/go_tls_trace.c

//go:build linux

package sensor

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"sync/atomic"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
)

// HttpEvent is the Go representation of an event emitted by the eBPF program.
// Published to Redis as JSON.
type HttpEvent struct {
	PID         uint32 `json:"pid"`
	TID         uint32 `json:"tid"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	StatusCode  uint16 `json:"status_code"`
	TimestampNs int64  `json:"timestamp_ns"`
}

// httpEventC mirrors the C struct http_event_t defined in bpf/http_trace.c.
//
// Layout (x86-64 little-endian, clang default packing):
//
//	__u32 pid;           offset  0, 4 bytes
//	__u32 tid;           offset  4, 4 bytes
//	__u64 timestamp_ns;  offset  8, 8 bytes
//	__u16 status_code;   offset 16, 2 bytes
//	char  method[8];     offset 18, 8 bytes
//	char  path[128];     offset 26, 128 bytes
//	tail padding         6 bytes  → sizeof = 160
//
// This struct is only used with encoding/binary.Read; field order must match.
type httpEventC struct {
	Pid         uint32
	Tid         uint32
	TimestampNs uint64
	StatusCode  uint16
	Method      [8]byte
	Path        [128]byte
	_           [6]byte // tail padding to reach 160-byte alignment boundary
}

// eventSize is the canonical size of http_event_t including tail padding.
// Must match sizeof(struct http_event_t) as reported by clang.
const eventSize = 160

// liveSensor runs actual eBPF programs on a Linux kernel >= 5.8.
type liveSensor struct {
	cfg   Config
	log   *zap.Logger
	rdb   *redis.Client
	drift *DriftEngine
}

func newLiveSensor(cfg Config, log *zap.Logger) (*liveSensor, error) {
	rdb := redis.NewClient(&redis.Options{Addr: cfg.RedisAddr})
	drift := NewDriftEngine(DefaultDriftConfig(), log.Named("drift"))
	return &liveSensor{cfg: cfg, log: log, rdb: rdb, drift: drift}, nil
}

func (s *liveSensor) Run(ctx context.Context) error {
	s.log.Info("Live eBPF sensor starting — removing RLIMIT_MEMLOCK")

	// Allow the process to lock unlimited memory for eBPF maps.
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock: %w", err)
	}

	// Start the drift detection engine. It runs until ctx is cancelled.
	go s.drift.Run(ctx, s.publishDriftAlert)

	// Launch the comprehensive sensor (tracepoints + TLS uprobes) in parallel.
	// It shares the same Redis stream and runs independently of the kprobe path.
	go s.runSensorPrograms(ctx)

	// Launch the Go TLS sensor (crypto/tls uprobes) in parallel.
	// Graceful: if no suitable Go binary is found, this goroutine exits silently.
	go s.RunGoTLSPrograms(ctx)

	// Load the pre-compiled eBPF object generated by bpf2go from http_trace.c.
	// HttpTraceObjects and LoadHttpTraceObjects are generated at build time via:
	//   //go:generate go run github.com/cilium/ebpf/cmd/bpf2go ...
	objs := HttpTraceObjects{}
	if err := LoadHttpTraceObjects(&objs, &ebpf.CollectionOptions{}); err != nil {
		return fmt.Errorf("load eBPF objects: %w", err)
	}
	defer objs.Close()

	// Attach kprobe to tcp_sendmsg.
	// tcp_sendmsg(struct sock *sk, struct msghdr *msg, size_t size)
	kp, err := link.Kprobe("tcp_sendmsg", objs.KprobeTcpSendmsg, nil)
	if err != nil {
		return fmt.Errorf("attach kprobe/tcp_sendmsg: %w", err)
	}
	defer kp.Close()

	s.log.Info("kprobe attached to tcp_sendmsg")

	// Open the ring buffer reader for the 'events' map.
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		return fmt.Errorf("open ring buffer: %w", err)
	}
	defer rd.Close()

	s.log.Info("Ring buffer reader open — streaming events to Redis",
		zap.String("stream", s.cfg.RedisStream),
	)

	// Close the ring buffer when the context is cancelled so rd.Read unblocks.
	go func() {
		<-ctx.Done()
		rd.Close()
	}()

	// processedCount tracks total events for periodic throughput logging.
	var processedCount atomic.Int64

	for {
		record, err := rd.Read()
		if err != nil {
			if ctx.Err() != nil {
				return nil // clean shutdown
			}
			s.log.Warn("ring buffer read error", zap.Error(err))
			continue
		}

		evt, err := parseRawEvent(record.RawSample)
		if err != nil {
			s.log.Warn("failed to parse event", zap.Error(err))
			continue
		}

		if err := s.publishEvent(ctx, evt); err != nil {
			s.log.Error("failed to publish event to Redis", zap.Error(err))
		}

		// Feed the drift engine with this endpoint observation.
		if evt.Path != "" {
			s.drift.Observe(evt.Path)
		}

		// Periodic throughput logging every 1000 events.
		n := processedCount.Add(1)
		if n%1000 == 0 {
			s.log.Info("kprobe event throughput checkpoint",
				zap.Int64("total_events", n),
			)
		}
	}
}

// parseRawEvent deserialises the binary C struct from the eBPF ring buffer.
//
// The raw bytes are a packed representation of struct http_event_t.
// We use encoding/binary (little-endian) which matches x86-64 kernel layout.
// JSON unmarshal is WRONG here — the kernel writes a C struct, not JSON.
func parseRawEvent(raw []byte) (*HttpEvent, error) {
	if len(raw) < eventSize {
		return nil, fmt.Errorf("record too short: got %d bytes, want %d", len(raw), eventSize)
	}

	var c httpEventC
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &c); err != nil {
		return nil, fmt.Errorf("binary.Read: %w", err)
	}

	return &HttpEvent{
		PID:         c.Pid,
		TID:         c.Tid,
		TimestampNs: int64(c.TimestampNs),
		StatusCode:  c.StatusCode,
		Method:      nullTermString(c.Method[:]),
		Path:        nullTermString(c.Path[:]),
	}, nil
}

// nullTermString converts a null-padded byte slice to a Go string.
func nullTermString(b []byte) string {
	return strings.TrimRight(string(b), "\x00")
}

func (s *liveSensor) publishEvent(ctx context.Context, evt *HttpEvent) error {
	evt.TimestampNs = time.Now().UnixNano()
	payload, err := json.Marshal(evt)
	if err != nil {
		return fmt.Errorf("json marshal: %w", err)
	}
	return s.rdb.XAdd(ctx, &redis.XAddArgs{
		Stream: s.cfg.RedisStream,
		Values: map[string]interface{}{"data": string(payload)},
	}).Err()
}

// publishDriftAlert marshals a DriftAlert and writes it to the Redis stream.
// The remediation-brain consumes drift_alert events to trigger LangGraph workflows.
func (s *liveSensor) publishDriftAlert(ctx context.Context, alert DriftAlert) error {
	payload, err := json.Marshal(alert)
	if err != nil {
		return fmt.Errorf("json marshal drift alert: %w", err)
	}
	return s.rdb.XAdd(ctx, &redis.XAddArgs{
		Stream: s.cfg.RedisStream,
		Values: map[string]interface{}{"data": string(payload)},
	}).Err()
}

// DriftStats returns a snapshot of all endpoint drift states.
// Called from the /drift/stats HTTP handler in main.go.
func (s *liveSensor) DriftStats() []EndpointStats {
	return s.drift.Stats()
}

// ── Comprehensive sensor (sensor.c) ──────────────────────────────────────────
// Loads and attaches the programs from bpf/sensor.c:
//   - tracepoints: sys_enter_sendto, sys_enter_recvfrom, sys_exit_recvfrom
//   - uprobes:     SSL_write entry, SSL_read entry+exit
// Runs as a goroutine alongside the existing kprobe/tcp_sendmsg loop.

// SensorEvent is the Go representation of sensor_event_t from bpf/sensor.c.
// Published to the same Redis stream as HttpEvent, differentiated by source/direction.
type SensorEvent struct {
	PID         uint32 `json:"pid"`
	TID         uint32 `json:"tid"`
	Method      string `json:"method"`
	Path        string `json:"path"`
	StatusCode  uint16 `json:"status_code"`
	TimestampNs int64  `json:"timestamp_ns"`
	Source      string `json:"source"`    // "plain" | "tls" | "go_tls"
	Direction   string `json:"direction"` // "egress" | "ingress"
}

// sensorEventC mirrors struct sensor_event_t defined in bpf/sensor.c.
//
// Layout (x86-64 little-endian, clang default packing):
//
//	__u32  pid;           offset  0,  4 bytes
//	__u32  tid;           offset  4,  4 bytes
//	__u64  timestamp_ns;  offset  8,  8 bytes
//	__u16  status_code;   offset 16,  2 bytes
//	__u8   source;        offset 18,  1 byte
//	__u8   direction;     offset 19,  1 byte
//	char   method[8];     offset 20,  8 bytes
//	char   path[128];     offset 28, 128 bytes
//	__u8   _pad[4];       offset 156, 4 bytes → sizeof = 160
type sensorEventC struct {
	Pid         uint32
	Tid         uint32
	TimestampNs uint64
	StatusCode  uint16
	Source      uint8
	Direction   uint8
	Method      [8]byte
	Path        [128]byte
	_           [4]byte // tail padding
}

const sensorEventSize = 160 // must equal sizeof(struct sensor_event_t)

// sourceString converts the C SOURCE_* constant to a human-readable string.
func sourceString(s uint8) string {
	switch s {
	case 1:
		return "tls"
	case 2:
		return "go_tls"
	default:
		return "plain"
	}
}

// directionString converts the C DIR_* constant to a human-readable string.
func directionString(d uint8) string {
	if d == 1 {
		return "ingress"
	}
	return "egress"
}

// parseSensorEvent deserialises a raw ring buffer record from sensor.c into
// a SensorEvent. The raw bytes are a C struct — binary.LittleEndian matches
// x86-64 kernel layout.
func parseSensorEvent(raw []byte) (*SensorEvent, error) {
	if len(raw) < sensorEventSize {
		return nil, fmt.Errorf("sensor record too short: got %d bytes, want %d", len(raw), sensorEventSize)
	}

	var c sensorEventC
	if err := binary.Read(bytes.NewReader(raw), binary.LittleEndian, &c); err != nil {
		return nil, fmt.Errorf("binary.Read sensor event: %w", err)
	}

	return &SensorEvent{
		PID:         c.Pid,
		TID:         c.Tid,
		TimestampNs: int64(c.TimestampNs),
		StatusCode:  c.StatusCode,
		Source:      sourceString(c.Source),
		Direction:   directionString(c.Direction),
		Method:      nullTermString(c.Method[:]),
		Path:        nullTermString(c.Path[:]),
	}, nil
}

// findLibSSL returns the path to libssl.so on the current host by probing
// well-known locations. Returns an error if OpenSSL is not installed.
// The uprobe attachment in runSensorPrograms is skipped gracefully if this fails.
func findLibSSL() (string, error) {
	candidates := []string{
		"/usr/lib/x86_64-linux-gnu/libssl.so.3",
		"/usr/lib/x86_64-linux-gnu/libssl.so.1.1",
		"/usr/lib/libssl.so.3",
		"/usr/lib/libssl.so.1.1",
		"/usr/local/lib/libssl.so.3",
		"/usr/local/lib/libssl.so.1.1",
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}
	return "", fmt.Errorf("libssl.so not found in standard locations")
}

// publishSensorEvent marshals a SensorEvent to JSON and writes it to Redis Streams.
func (s *liveSensor) publishSensorEvent(ctx context.Context, evt *SensorEvent) error {
	evt.TimestampNs = time.Now().UnixNano()
	payload, err := json.Marshal(evt)
	if err != nil {
		return fmt.Errorf("json marshal sensor event: %w", err)
	}
	return s.rdb.XAdd(ctx, &redis.XAddArgs{
		Stream: s.cfg.RedisStream,
		Values: map[string]interface{}{"data": string(payload)},
	}).Err()
}

// runSensorPrograms loads SensorObjects (generated from bpf/sensor.c by bpf2go),
// attaches syscall tracepoints and OpenSSL uprobes, and reads events from the
// ring buffer, publishing each to Redis.
//
// Called as a goroutine from Run(). Errors are logged but do not crash the
// main sensor loop — the kprobe/tcp_sendmsg path continues regardless.
// TLS uprobe attachment is skipped gracefully if libssl is not present.
func (s *liveSensor) runSensorPrograms(ctx context.Context) {
	log := s.log.Named("sensor2")

	sObjs := SensorObjects{}
	if err := LoadSensorObjects(&sObjs, &ebpf.CollectionOptions{}); err != nil {
		log.Error("failed to load sensor eBPF objects — tracepoints+uprobes disabled", zap.Error(err))
		return
	}
	defer sObjs.Close()

	var closers []func()

	// ── Syscall tracepoints ────────────────────────────────────────────────────

	tpSend, err := link.Tracepoint("syscalls", "sys_enter_sendto", sObjs.TpSendto, nil)
	if err != nil {
		log.Warn("failed to attach tracepoint sys_enter_sendto", zap.Error(err))
	} else {
		closers = append(closers, func() { tpSend.Close() })
		log.Info("tracepoint attached: sys_enter_sendto")
	}

	tpRecvEnter, err := link.Tracepoint("syscalls", "sys_enter_recvfrom", sObjs.TpEnterRecvfrom, nil)
	if err != nil {
		log.Warn("failed to attach tracepoint sys_enter_recvfrom", zap.Error(err))
	} else {
		closers = append(closers, func() { tpRecvEnter.Close() })
		log.Info("tracepoint attached: sys_enter_recvfrom")
	}

	tpRecvExit, err := link.Tracepoint("syscalls", "sys_exit_recvfrom", sObjs.TpExitRecvfrom, nil)
	if err != nil {
		log.Warn("failed to attach tracepoint sys_exit_recvfrom", zap.Error(err))
	} else {
		closers = append(closers, func() { tpRecvExit.Close() })
		log.Info("tracepoint attached: sys_exit_recvfrom")
	}

	// ── OpenSSL uprobes ───────────────────────────────────────────────────────
	// Graceful: if libssl is not installed, log and continue with tracepoints only.

	libsslPath, err := findLibSSL()
	if err != nil {
		log.Warn("libssl not found — TLS uprobe capture disabled", zap.Error(err))
	} else {
		ex, err := link.OpenExecutable(libsslPath)
		if err != nil {
			log.Warn("failed to open libssl for uprobes", zap.String("path", libsslPath), zap.Error(err))
		} else {
			// uprobe: SSL_write — fires before encryption; buf is plaintext
			upSSLWrite, err := ex.Uprobe("SSL_write", sObjs.UprobeSslWrite, nil)
			if err != nil {
				log.Warn("failed to attach uprobe SSL_write", zap.Error(err))
			} else {
				closers = append(closers, func() { upSSLWrite.Close() })
				log.Info("uprobe attached: SSL_write", zap.String("lib", libsslPath))
			}

			// uprobe entry: SSL_read — saves buf pointer to map before kernel fills it
			upSSLReadEnter, err := ex.Uprobe("SSL_read", sObjs.UprobeSslReadEnter, nil)
			if err != nil {
				log.Warn("failed to attach uprobe SSL_read (entry)", zap.Error(err))
			} else {
				closers = append(closers, func() { upSSLReadEnter.Close() })
				log.Info("uprobe attached: SSL_read (entry)", zap.String("lib", libsslPath))
			}

			// uretprobe exit: SSL_read — reads decrypted data after OpenSSL fills buf
			upSSLReadExit, err := ex.Uretprobe("SSL_read", sObjs.UprobeSslReadExit, nil)
			if err != nil {
				log.Warn("failed to attach uretprobe SSL_read (exit)", zap.Error(err))
			} else {
				closers = append(closers, func() { upSSLReadExit.Close() })
				log.Info("uretprobe attached: SSL_read (exit)", zap.String("lib", libsslPath))
			}
		}
	}

	defer func() {
		for _, closeFn := range closers {
			closeFn()
		}
	}()

	// ── Ring buffer reader ─────────────────────────────────────────────────────

	rd, err := ringbuf.NewReader(sObjs.Events)
	if err != nil {
		log.Error("failed to open sensor ring buffer", zap.Error(err))
		return
	}
	defer rd.Close()

	log.Info("sensor ring buffer open — streaming syscall+TLS events to Redis",
		zap.String("stream", s.cfg.RedisStream),
	)

	go func() {
		<-ctx.Done()
		rd.Close()
	}()

	// processedCount tracks total events for periodic throughput logging.
	var processedCount atomic.Int64

	for {
		record, err := rd.Read()
		if err != nil {
			if ctx.Err() != nil {
				return // clean shutdown
			}
			log.Warn("sensor ring buffer read error", zap.Error(err))
			continue
		}

		evt, err := parseSensorEvent(record.RawSample)
		if err != nil {
			log.Warn("failed to parse sensor event", zap.Error(err))
			continue
		}

		// Feed the drift engine with this endpoint observation.
		if evt.Path != "" {
			s.drift.Observe(evt.Path)
		}

		if err := s.publishSensorEvent(ctx, evt); err != nil {
			log.Error("failed to publish sensor event to Redis", zap.Error(err))
		}

		// Periodic throughput logging every 1000 events.
		n := processedCount.Add(1)
		if n%1000 == 0 {
			log.Info("sensor2 event throughput checkpoint",
				zap.Int64("total_events", n),
			)
		}
	}
}
